excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://WeLoveSleep.github.io
title: We Love Sleep
tagline: For the Love of Sleep
description: We love sleeping and beautiful bedrooms. When we aren't sleeping we love talking, writing and thinking about sleep and beautiful bedrooms!
paginate: 5
